# Generated by Django 2.2.3 on 2019-07-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
