# Generated by Django 2.2.3 on 2019-07-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20190713_2027'),
        ('core', '0002_auto_20190713_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='produto',
            field=models.ManyToManyField(to='produtos.Produto'),
        ),
    ]
