# Generated by Django 2.2.3 on 2019-07-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('core', '0003_estabelecimento_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='comentario',
            field=models.ManyToManyField(to='comentarios.Comentario'),
        ),
    ]
