# Generated by Django 2.2.3 on 2019-07-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('core', '0004_estabelecimento_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='avaliacao',
            field=models.ManyToManyField(to='avaliacoes.Avaliacao'),
        ),
    ]
