# Generated by Django 2.2.3 on 2019-07-15 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_estabelecimento_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enderecos.Endereco'),
        ),
    ]
