# Generated by Django 2.2.3 on 2019-07-25 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190714_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estabelecimento',
            old_name='avaliacao',
            new_name='avaliacaoes',
        ),
        migrations.RenameField(
            model_name='estabelecimento',
            old_name='comentario',
            new_name='comentarios',
        ),
    ]
