# Generated by Django 2.2.3 on 2019-07-25 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190724_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estabelecimento',
            old_name='produto',
            new_name='produtos',
        ),
    ]
