# Generated by Django 2.2.3 on 2019-07-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190724_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='estabelecimentos'),
        ),
    ]
