# Generated by Django 2.2.3 on 2019-07-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='disponivel',
        ),
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
